import { readFileSync } from 'node:fs';
import { createClient } from '@supabase/supabase-js';
const env = Object.fromEntries(readFileSync('.env','utf8').split('\n').filter(l=>l.includes('=')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i).trim(), l.slice(i+1).trim().replace(/^["']|["']$/g,'')];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {auth:{persistSession:false}});
const t0=Date.now();
const { count, error } = await sb.from('ground_handling_irregularity_report').select('*',{count:'exact',head:true});
console.log('report count:', count, 'err:', error?.message, 'ms:', Date.now()-t0);
const t1=Date.now();
const { data, error: e2 } = await sb.from('ground_handling_irregularity_report').select('id,created_at,title,status,severity,main_category').order('created_at',{ascending:false}).order('id',{ascending:false}).limit(51);
console.log('list page rows:', data?.length, 'err:', e2?.message, 'ms:', Date.now()-t1);
const { count: jc } = await sb.from('joumpa_reports_sync').select('*',{count:'exact',head:true});
console.log('joumpa count:', jc);
const { count: cc } = await sb.from('report_comments').select('*',{count:'exact',head:true});
console.log('comments count:', cc);
